using System.Reflection;
[assembly: AssemblyTitle("GldeTK")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("GldeTK")]
[assembly: AssemblyCopyright("Copyright © Nikolai Voronin 2016")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: AssemblyVersion("1.0.*")]
